const SUBMIT_SEARCH = 'search/SUBMIT_SEARCH',
      SUBMIT_SUCCESS = 'search/SUBMIT_SUCCESS',
      SUBMIT_ERROR = 'search/SUBMIT_ERROR',
      SUBMIT_PENDING = 'search/SUBMIT_PENDING',
      SET_PAGE = 'search/SET_PAGE',
      UPDATE_HITS = 'search/UPDATE_HITS',
      UPDATE_PAGE = 'search/UPDATE_PAGE'

export default {
  SUBMIT_SEARCH,
  SUBMIT_SUCCESS,
  SUBMIT_ERROR,
  SUBMIT_PENDING,
  SET_PAGE,
  UPDATE_PAGE,
  UPDATE_HITS
}